### ISSUE TITLE
Docs - Table mapping Kyverno policies to Pepr policies

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-core#418]
As we work to transition customers familiar with BB to UDS core, there is a constant question about why we are replacing Kyverno with Pepr and a request for a visual table that maps Kyberno policies to Pepr policies that replace them. 

https://github.com/defenseunicorns/uds-core/tree/main/src/pepr/policies

**Comment by mjnagel** [comment]
@Madeline-UX is there an ask here that goes beyond the [current table](https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/policies/README.md) you linked? I'm thinking a few things that would be useful:
- Reduce scope of table (maybe we reduce this to just the implemented policies)
- Ensure this surfaces to the docs site (relocate to docs folder rather than where it is)
- Separate out the exemption piece (unsure if this would be helpful or make it harder)

**Comment by mjnagel** [comment]
Scoping to this for now:
- Eliminate non-implemented policies from the table
- Relocate doc to ensure it is surfaced on the docs site (`docs/` folder)
- Either in the table or separately, identify mutations that are done for policies

Exemption documentation will likely be added as part of https://github.com/defenseunicorns/uds-core/issues/382
