### ISSUE TITLE
Best practices for local development

### ISSUE THREAD

**Issue by cpepper96** [defenseunicorns/uds-core#484]
Hi y'all 👋

I stumbled across this project the other day and reallyyy like the idea of being able to spin up a local cluster with Istio/Keycloak just by running `uds deploy k3d-core-slim-dev:0.22.2`. Having some issues though deploying my team's helm chart to this cluster probably due to me not being familiar with Zarf. 

So questions I had were:
1. Is this an appropriate use case for this tool? We're developing an app to be deployed w/ Big Bang on C1
2. Can I deploy Helm charts or do I need to use Zarf packages?
3. Can I use a private container registry and/or Iron Bank or do I need to use the Zarf container registry?

Any help is appreciated!

**Comment by mjnagel** [comment]
Hey @cpepper96 - hopefully we'll have a Slack and/or GitHub discussions setup at some point but for now happy to answer those here in the issue:
1. The slim-dev bundle you mentioned is great for doing quick dev for apps deployed on top of UDS Core. Big Bang and UDS Core have a number of overlaps but uds-core does have some different opinionation and the usage of zarf/pepr which might mean your experiences working with it might not translate 1:1 to a Big Bang cluster.
2. Technically you could do either but it's going to be a bit different/harder without zarf. For example, when you deploy anything onto a cluster that has zarf initialized all images will default to trying to pull from the zarf registry. You can use [ignore annotations](https://docs.zarf.dev/ref/init-package/#excluding-resources-from-zarf-agent) on all your pods/resources to make sure they pull from the original locations if you want to just use helm/manifests more directly.
3. Related to ^ answer - if you use ignore annotations you can use the original registries. Otherwise the expectation is that you are deploying via zarf.

Hope that helps! Definitely let us know if we can help with any other questions or improve the experience in any way. [Zarf docs](https://docs.zarf.dev/getting-started/understanding) might be a good place to learn some of the zarf specifics at play here, and there is a zarf slack channel on the k8s slack if you have more generic zarf questions.

**Comment by cpepper96** [comment]
Thanks for the response @mjnagel! I see y'all have set up GitHub discussions so I'll post any further questions I have there.
