### ISSUE TITLE
 Make the Istio Passthrough Gateway Optional

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/uds-core#510]
### Is your feature request related to a problem? Please describe.
As a bundle deployer who doesn't need the passthrough gateway, I would like the ability to opt out

### Describe the solution you'd like

- **Given** a deployment of UDS Core bundle
- **When** I create / deploy the bundle
- **Then** I have the ability to opt out of the passthrough gateway that isn't needed

### Describe alternatives you've considered
UDS Task to `zarf package remove uds-core --components istio-passthrough-gateway --confirm`

**Comment by mjnagel** [comment]
I think based on default needs of uds-core and swf this should probably be an optional (off by default) component - should be a small switch, and end users could still opt-in to using it with their bundle. This _WOULD_ be a breaking change and should be noted as such + ensure we have documentation around how to use this gateway.

**Comment by mjnagel** [comment]
Updating to identify path forward:
- Change the passthrough-gateway from `required: true` to `required: false`, specifically commenting it as an optional component since uds-core does not require it but other packages may want it
- Identify this as a breaking change (we use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with--to-draw-attention-to-breaking-change))
- Ensure that we are still testing the deployment of the passthrough gateway in one of our CI tests - this might make the most sense in our [demo-bundle](https://github.com/defenseunicorns/uds-core/blob/main/bundles/k3d-standard/uds-bundle.yaml) by leveraging [uds-cli `optionalComponents`](https://uds.defenseunicorns.com/cli/quickstart-and-usage/#declarative-syntax). This bundle is used in our PR tests so it would be validated often.
