### ISSUE TITLE
Add nightly CI testing on RKE2

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#726]
Related to https://github.com/defenseunicorns/uds-core/issues/213

Currently we do nightly testing on EKS. In order to expand our testing posture we should also test on RKE2. The EKS testing is contained in these locations:
- Workflow: https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/nightly-testing.yaml
- Nightly bundle: https://github.com/defenseunicorns/uds-core/tree/main/.github/bundles
- Test infra: https://github.com/defenseunicorns/uds-core/tree/main/.github/test-infra/buckets-iac
- IAC task file: https://github.com/defenseunicorns/uds-core/blob/main/tasks/iac.yaml

Definition of done: Nightly test added to spin up RKE2 and deploy core (all flavors, matrixed) on it. This should use external S3 buckets where required. For this initial iteration we should keep it as simple as possible:
1. Leverage images built by the image builder: https://github.com/defenseunicorns/uds-rke2-image-builder (these are published in the CI AWS account)
2. Leverage basic terraform to spin up the cluster: Since this is ephemeral we should focus on MVP for now. Potentially could reuse some of the terraform from the [image builder](https://github.com/defenseunicorns/uds-rke2-image-builder/tree/main/.github/test-infra/rke2-cluster).
3. Use as few AWS dependencies as possible to start. Example: rather than setting up IRSA, just use key based auth for buckets. These may be future enhancements to the RKE2 test but should not be in scope for this initial setup.

**Comment by noahpb** [comment]
Terraform has been validated locally. A multi-node cluster can be deployed with a fresh build of uds-core on top. A mix between the rke2 open source terraform module and IaC from the image builder repository was used. IRSA was found to be necessary due to restrictions in our CI AWS account. Appropriate external infrastructure (such as resources to support OIDC and s3 storage, networking and IAM roles) are also included. 

New pipeline is currently pending validation in [this](https://github.com/defenseunicorns/uds-core/pull/808) PR. Note that the PR includes additional changes to task files and repo structure to support testing across multiple K8s distributions.

**Comment by noahpb** [comment]
All CI tests passing, moving this to in review.

**Comment by noahpb** [comment]
Currently validating irsa functionality before asking for another review.
