### ISSUE TITLE
Setup SSO for NeuVector, disable basic auth

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#91]
### Is your feature request related to a problem? Please describe.

Deploying UDS Core by default provides NeuVector with a default `admin` user (password `admin`).

### Describe the solution you'd like

Automate the SSO setup for NeuVector using the UDS Package CR, and (if possible) disable basic/local auth. Map existing groups/roles to NeuVector roles as applicable (admin/auditor should get different permissions in NeuVector).

Note: The neuvector prometheus exporter does require auth as of last check, so we will need to identify a way to handle this NPE account, or maintain basic auth for metrics only (read-only).

**Comment by blancharda** [comment]
This issue may need an update now that IDAM/keycloak is enabled.

**Comment by mjnagel** [comment]
Thanks @blancharda - updated to capture SSO setup for NeuVector being the goal here.

**Comment by chance-coleman** [comment]
@MxNxPx @mjnagel @rjferguson21 

Neuvector SSO configuration automation requires a larger conversation about it's approach.I was able to setup pepr managed client creation for neuvector, however not SSO because there is a dependency on that client being created before deploying neuvector which is how the client is created. Doing something similar to grafana is ideal, however not possible in it's current implementation. Grafana waits for the creation of the client secret before it creates/installs it's deployment, then uses the secret for configuration purposes. Manipulating the upstream Neuvector chart is one option, otherwise utilizing Pepr could also be an option for configuring Neuvector SSO.

**Comment by rjferguson21** [comment]
@mjnagel @UnicornChance @MxNxPx I was able to get this working with Micah's suggestion but it appears that it is not possible to disable local auth? I am surprised by that but maybe I am missing something?

**Comment by mjnagel** [comment]
Good find by @MxNxPx - https://www.suse.com/support/kb/doc/?id=000021082 - may be able to use this ENV to disable the default admin user. Will need separate convo on the monitoring user probably, but I think that will depend on changes upstream.

**Comment by rjferguson21** [comment]
Thanks @MxNxPx, env var of `NO_DEFAULT_ADMIN=1` worked.
